readme.md
Otherwise, clicking the Read Me link 404s at ```https://github.com/wesbos/JavaScript30/blob/master/JavaScript30.com```
=> Add Transport Protocol to readme Link

02 - JS + CSS Clock/index-FINISHED.html, 02 - JS + CSS Clock/index-START.html, 02 - JS + CSS Clock/index.html
Hi @wesbos, this is a simple PR to fix the title of the page in the 2nd challenge from `"Document"` to `"JS + CSS Clock"`.
=> Fixes title of 2nd challenge

04 - Array Cardio Day 1/index-FINISHED.html
A random selection of female inventors for the dataset along with proposed change in const name.
=> female inventors + change in const name

04 - Array Cardio Day 1/index-START.html
This is a random selection of female inventors for the dataset
=> adding women inventors

24 - Sticky Nav/index-START.html, 24 - Sticky Nav/style-START.css
Reset the contents of index-START and style-START to reflect the
contents before running through the video.
=> 24 - Sticky Nav: reset index and style START

13 - Slide in on Scroll/index-START.html
Noticed the answer in the start file.
=> removed answer code from index-START.html Ex 13

11 - Custom Video Player/index.html
=> Modify a minor mistake.

07 - Array Cardio Day 2/index-START.html
Love the program so far. I generally like to try my hand at exercises before watching the accompanying video, but I found on this exercise that the question "Is at least one person 19?" did not mean to me what Wes expected it to mean (i.e. "Is someone _exactly_ 19?" vs "Is someone _at least_ 19?"). This small edit will add some clarity.
=> Clarify questions in exercise 7

04 - Array Cardio Day 1/index-FINISHED.html
Hi Wes, thank you again for an awesome series. I'm following it together with over 10 JavaScript developers.
I've just found a small mistake in the 7th exercise - sort. The last names should come before the first names to reflect the original array(`people`). You got it right the the video 👍
=> Fix the order in the sort exercise

04 - Array Cardio Day 1/index-START.html
=> Flavours array

04 - Array Cardio Day 1/index-START.html
Mr. Elk Black is missing a comma in Day 4's `people` array.
=> Add missing comma

10 - Hold Shift and Check Checkboxes/index-FINISHED.html, 10 - Hold Shift and Check Checkboxes/index-START.html
Little improvement, sets the page title of the **Hold Shift and Check Checkboxes** exercise.
=> Sets Hold Shift and Check Checkboxes page title

readme.md
=> add Adriana Rios to readme

readme.md
=> add Michael Einsohn to readme

readme.md
=> Added Arjun Khode's blog to readme

readme.md
=> Hi, @wesbos here's my submission. Let me know if there's any issues :)

11 - Custom Video Player/style.css
property box-shadow is overwritten
=> rm overwritten styles

02 - JS and CSS Clock/index-FINISHED.html, 02 - JS and CSS Clock/index-START.html, 11 - Custom Video Player/style.css, 16 - Mouse Move Shadow/index-finished.html, 16 - Mouse Move Shadow/index-start.html, 17 - Sort Without Articles/index-FINISHED.html, 17 - Sort Without Articles/index-START.html, 21 - Geolocation/index-FINISHED.html, 21 - Geolocation/index-START.html, 23 - Speech Synthesis/style.css, 26 - Stripe Follow Along Nav/index-FINISHED.html, 26 - Stripe Follow Along Nav/index-START.html, 28 - Video Speed Controller/style.css
hide visible vertical scrollbar
body 100vh + default margins > window height
win10 chrome
=> hide vertical scrollbar

readme.md
Hi, @wesbos here is my PR. Please let me know if there is any issues, thank you 😄 
Amelie 😄 
… thank you!
👋👋👋👋👋👋👋👋👋👋👋👋👋👋
👋👋👋👋👋👋👋👋👋👋👋👋👋👋
=> Hello PR from Taiwan

11 - Custom Video Player/style.css
=> fixed type-o in webkit-slider-runnable-track

13 - Slide in on Scroll/index-FINISHED.html
=> removed e parameter

28 - Video Speed Controller/index-FINISHED.html, 28 - Video Speed Controller/index-START.html
Hey! I just realized you don't accept PRs, but still wanted to let you know the dropbox video link from lesson 28 seems to be broken. Thanks for a cool course!
=> video link appears broken

20 - Speech Detection/index-FINISHED.html
I have Russian settings on my browser but I wanted to speak English and that's how I have fixed it.
👋👋👋👋👋👋👋👋👋👋👋👋👋👋
👋👋👋👋👋👋👋👋👋👋👋👋👋👋
=> Saying to browser listen for english.

readme.md
Added my links to the repo and the working exercises
=> Adding my link

readme.md
=> Rayhatron blog

readme.md
This is my approach to finish 30 day JavaScript challenge. I hope everyone can benefit from it.
👋👋👋👋👋👋👋👋👋👋👋👋👋👋
👋👋👋👋👋👋👋👋👋👋👋👋👋👋
=> Add link to my blog so everyone can learn from it. 

readme.md
To add to the ever growing lessons learned going through JS30.
=> Added link to my blog

readme.md
=> add Dustin Hsiao to readme

14 - JavaScript References VS Copying/index-START.html
Shown in starter file in video, missing from actual starter file.
=> Add person object to day 14 starter file

readme.md
Added a new bulletpoint with my name and links to CodePen and GitHub repo :)
=> Added to Readme.md my name

readme.md
=> Update readme.md and add my links

10 - Hold Shift and Check Checkboxes/index-FINISHED.html, 10 - Hold Shift and Check Checkboxes/index-START.html
Hi Wes,
I've found 2 typos and corrected them.
Regards,
Ela
=> corrected 2 typos

26 - Stripe Follow Along Nav/index-FINISHED.html, 26 - Stripe Follow Along Nav/index-START.html
Small update for link
**Fix for:** af466bbdb71615c076b14fc895e0b6625b19fdd6
=> Added small update for 26 lesson - link

readme.md
=> Modified readme for link to my solutions

16 - Mouse Move Shadow/index-finished.html, 19 - Webcam Fun/scripts-FINISHED.js, 22 - Follow Along Link Highlighter/style.css, 24 - Sticky Nav/index-FINISHED.html
Hi Wes,
I found few typos&whitespaces.
Thanks,
Ela
=> typos&whitespaces improvements

readme.md
Add my links of the gh-pages and lessons to README in community content.
=> Add my gh-pages and lessons to README

readme.md
=> Add community content - ClojureScript

readme.md
=> Add kizito's follow-along repo and notes

readme.md
Added a mention of my  A New Vue on #JavaScript30 blog series at https://davefollett.io
=> Added blog series to readme.md

readme.md
=> Alternative implementation using Stimulus JS

10 - Hold Shift and Check Checkboxes/index-START.html
=> Fix typo in index-START.html

readme.md
=> VannTile's JavaScript30 implementation

readme.md
=> update community content list

readme.md
The comments at the top of each TypeScript file highlights some of my takeaways from each project.
=> Adding my TypeScript implementation to the readme

02 - JS and CSS Clock/index-START.html
=> Update the url of background image to https

readme.md
awesome course!!
thinks wesbos~~
=> add my all practices link to README.md

readme.md
=> add Dart 2.0 version

readme.md
Adding Mugilan's Solutions for the Challenge
=> Add Mugilan's Solution

readme.md
Added Ayush Gupta's implementation of JavaScript30 challenge with some add-ons & updated design.
Link: [JavaScript30 - Ayush Gupta](https://javascript30.ayushgupta.tech/)
=> Add a link in community resource

04 - Array Cardio Day 1/index-FINISHED.html, 04 - Array Cardio Day 1/index-START.html
Dear Wes,
Thank you very much for this awesome course, I'm learning a lot from it!
I understand the video/code might not be updated in order to keep things consistent, but I'd still like to propose this small change. In the current version of the source code the order of items in the 'people' array is the same as that of the output of exercise 7, thus the difference is not quite visible, in my opinion. Maybe it would make sense even without a video update?
Thank you for your consideration!
Best,
Lilla Pulay
=> Suggestion for 'people' array of day 4

28 - Video Speed Controller/index-FINISHED.html
There is a paragraph tag that is not related to our aim and also not found in the js 30 video
=> Remove unnecessary <p> tag

readme.md
Before, a panel would stay activated even when a new one was clicked. Now it deactivates so that always only one is activated.
=> [Readme] Add a link to a fix of panels' deactivation

readme.md
Implement JavaScript 30 in RxJS and Angular.   
I am going through JavaScript 30 tutorial but using RxJS and Angular to implement. I have finished 8 exercises so far.
=> chore: implement JavaScript 30 in RxJS and Angular

readme.md
Added period and removed extra space from Readme.md file for proper Documentation.
=> Changes made in the Readme file

readme.md
乔木首次提交中文视频链接
hello,i am 乔木(Qiaomu)
=>  I recorded your javascript30 Chinese explanation video on the video platform in China

readme.md
add my project link in the readme
=> add my project link in the readme

readme.md
=> fix: link and typos in readme
