wesbos/JavaScript30

- 02 - JS + CSS Clock/index-FINISHED.html
Added the instant call "setDate" so you don't need to wait 1 second for first "setInterval".
> add the instant function call

- 01 - JavaScript Drum Kit/index.html
- 02 - JS + CSS Clock/index-FINISHED.html
- 02 - JS + CSS Clock/index-START.html
- 02 - JS + CSS Clock/index.html
- 04 - Array Cardio Day 1/index-FINISHED.html
- 04 - Array Cardio Day 1/index-START.html
- 05 - Flex Panel Gallery/index-FINISHED.html
- 06 - Type Ahead/index-FINISHED.html
- 06 - Type Ahead/style.css
- 07 - Array Cardio Day 2/index-START.html
- 09 - Dev Tools Domination/index-FINISHED.html
- 11 - Custom Video Player/style.css
- 13 - Slide in on Scroll/index-START.html
- 14 - JavaScript References VS Copying/index-FINISHED.html
- 15 - LocalStorage/style.css
- 20 - Speech Detection/index-FINISHED.html
- 22 - Follow Along Link Highlighter/style.css
- 26 - Stripe Follow Along Nav/index-FINISHED.html
- 28 - Video Speed Controller/style.css
Fix typos, missing/extra semicolon, duplicate css declaration.
> Fix typos and extra code

- 04 - Array Cardio Day 1/index-FINISHED.html
In your video you still sort on the first name of the array but you called it `aLast` and `bLast` but they where in the first position of the array like this: `const [aLast, aFirst]` when changed to `const [aFirst, aLast]` it will filter on the second part of the array. There for it will sort on the last name. 
To bad there is no way to pull request your video.
> 04 - Array Cardio Day 1, 7. sort Exercise | make it so it sorts on last name

- readme.md
Wes, thank you for a great innitiative.
> Fix typo: thank > thanks

- 03 - CSS Variables/index-FINISHED.html
- 03 - CSS Variables/index-START.html
`a` tag CSS was unused. Thanx 4 the Course @wesbos
> Unused CSS

- 04 - Array Cardio Day 1/index-FINISHED.html
- 04 - Array Cardio Day 1/index-START.html
- 07 - Array Cardio Day 2/index-FINISHED.html
- 07 - Array Cardio Day 2/index-START.html
Hi Wes, another couple of tiny improvements for the Array Cardio challenges 😉
> Massages Array Cardio challenges 💪

- 01 - JavaScript Drum Kit/style.css
This PR adds these things to 01-drumkit:
* converts all units to `rem` in css
* consistent spacing between rule and value (I'm find with taking out and just running on all files)
Visually the app is the same
Before:
After:
> converted to rems and added a space between `rule: value`

- 22 - Follow Along Link Highlighter/index-FINISHED.html
> change append() to appendChild()

- readme.md
> add Akinjide to readme

- 19 - Webcam Fun/style.css
Should be 'transform: rotate()', but it will not look like in the video
> Fix incorrect styles

- 05 - Flex Panel Gallery/index-FINISHED.html
- 05 - Flex Panel Gallery/index-START.html
- 06 - Type Ahead/style.css
- 10 - Hold Shift and Check Checkboxes/index-FINISHED.html
- 10 - Hold Shift and Check Checkboxes/index-START.html
- 27 - Click and Drag/style.css
> rm unused selectors

- 27 - Click and Drag/style.css
I don't know why it's happened (may be when we use box-shadow + overflow: scroll), but removing box-shadow (or setting overflow-x: **hidden** ) fixed it =)
> fix slider position

- 03 - CSS Variables/index-FINISHED.html
- 03 - CSS Variables/index-START.html
redundant CSS body selectors on lines 29/33 in START and FINISHED files
Consolidated into single selector.
Does not change the content of what's shown in the video, although the redundant body selectors are visible throughout the video as you revisit that part of the file.
> typo fix in 03 - CSS variables

- 30 - Whack A Mole/index-FINISHED.html
I found that if you don't call the parentNode the value of this point to the mole and the class was added to the hole. BTW, the remove class didn't worked when you trigger a click on the mole.
If someone wants to learn more https://developer.mozilla.org/es/docs/Web/API/Node/parentNode
Thank you for your great course!! I learned a lot of JS stuff!!
PD: This is my first PR if I went wrong on something I appreciate the feedback. Thank you all!
> Hide mole fixed on the challenge #30

- 05 - Flex Panel Gallery/index-FINISHED.html
- 05 - Flex Panel Gallery/index-START.html
Hey Wes!
Working my way through various lessons and noticed in this flex panels lesson that the image that was previously used for `.panel2`'s background-image is now missing. I've located what is hopefully a suitable replacement and changed it in the two HTML files.
Here is the replacement image suggested in the commit:
https://source.unsplash.com/rFKUFzjPYiQ/1500x1500
> fix missing unsplash.it background-image for .panel2

- 19 - Webcam Fun/package.json
- 20 - Speech Detection/package.json
- 21 - Geolocation/package.json
The 'files' argument was being passed to browser-sync inside single quotes. These aren't recognised when the script runs, so hot-reloading was only listening for changes on the html file.
Switching to escaped double quotes fixes this.
> Changed to escaped double-quotes to fix browser-sync

- 06 - Type Ahead/style.css
Hi, Wes Bos
thank you very much for your free tutorials Javascript30
I love to see your Javascript30 project!
however, I might found a unused <a>selector In 06 - Type Ahead CSS.
thank you.
> rm unused selector 'a'

- 19 - Webcam Fun/package.json
- 20 - Speech Detection/package.json
- 21 - Geolocation/package.json
browser-sync version 2.23.2 does not work in project 19, 20 or 21. In the browser just return "Cannot GET /index.html"
> $ npm list browser-sync
browser-sync@2.23.2
Version 2.23.1 of browser-sync works as expected.
Related issue https://github.com/BrowserSync/browser-sync/issues/1477
Simplest change seemed to be to limit the browser-sync version for now.
> Force browser-sync version less than 2.23.2 having issue in npm start

- 26 - Stripe Follow Along Nav/index-FINISHED.html
- 26 - Stripe Follow Along Nav/index-START.html
> Added small proposal for 26 lesson

- 19 - Webcam Fun/scripts-FINISHED.js
Replaced createObjectURL() with newer syntax. 
===================================
Well, if this PR is merged, it may be slightly different(only a single line) from the videos as createObjectURL() has been deprecated by major browsers. Just alerting @wesbos and others if not aware.
> createObjectURL() has been depreceated.

- readme.md
Thank you @wesbos for the JS lessons!
While learning TypeScript, I thought what better way than to learn it by re-implementing Wes Bos's JavaScript 30 lessons.
I'm still learning and hopefully I can make the TS implementation even better, more concise. I think I may have overdone it with the typings 💪
> Add link to implementation in TypeScript

- 02 - JS and CSS Clock/index-START.html
The background image url in '02 - JS & CSS Clock' returns "Invalid blur amount" in chrome, safari, and firefox. Removing the '0' from '50' in the url fixes this and allows the image to display.
> Day2backgroundimg

- 12 - Key Sequence Detection/index-FINISHED.html
- 12 - Key Sequence Detection/index-START.html
Replacing http by https in cornify.js import, to avoid insecure mixed content issues in some hosting providers.
> Replacing http by https in cornify.js

- 19 - Webcam Fun/index.html
The sound of `snap.mp3` used on day 19 when the user takes a photo is requested by the browser via HTTP.
This means that when this page is put on a server serving HTTPS, the browser will warn the user that connection is not totally secure like shown:
There's no need to use http since `wesbos.com` accepts HTTPS.
> [Day 19] Make request to snap.mp3 via HTTPS instead of HTTP

- 01 - JavaScript Drum Kit/style.css
In order to avoid mixed content(https://www.cloudflare.com/learning/ssl/what-is-mixed-content/) error, we can update the URL from HTTP to HTTPS.
> Update the url of background image to https

- 01 - JavaScript Drum Kit/style.css
The background image did not show without the quotes around the URL.
> Added quotes around background URL
